### PR TITLE
Fix govnames.json to reflect actual patterns.

### LINKED ISSUE #3096: Indexing Kythe go targets can't resolve imports.
```
$ ./kythe/extractors/bazel/extract.sh --go "$PWD" .comps
$ bazel-bin/kythe/go/indexer/cmd/go_indexer/go_indexer $(find bazel-out/k8-fastbuild/extra_actions/kythe/go/extractors/cmd/bazel/extra_action/kythe/go/ -name '**.kzip') | bazel-bin/kythe/go/storage/tools/write_entries/write_entries -graphstore /tmp/ky.gs                                                            
2018/10/02 22:59:48 Unable to resolve import path "kythe.io/kythe/go/services/xrefs"                                                                                                             
2018/10/02 22:59:48 Unable to resolve import path "kythe.io/kythe/go/storage/table"                                                                                                             
2018/10/02 22:59:48 Unable to resolve import path "bitbucket.org/creachadair/stringset"
...
```
Does the extractor work as expected? Or do I miss some mapping? Thank you!

### PR DESCRIPTION
**Pull request by robinp**
This lets sane extraction of kythe/go. There are some unpleasant file vnames left due to `cgo`, these can be rewritten as well later if bothers.

TESTED=indexed //kythe/go/...
Fixes #3096.

### CODE REVIEW

**Comment by robinp** [comment]
CC @creachadair @shahms

**Comment by robinp** [comment]
@shahms Thanks! I wonder why the buildbot checks don't trigger?

**Comment by salguarnieri** [comment]
Someone from the team has to manually trigger the buildbot for external contributors.

**Comment by danielmoy-google** [comment]
> Someone from the team has to manually trigger the buildbot for external contributors.

do we have a not-internal but still-whitelisted-for-buildbot group?

**Pull request merged**
