### PR TITLE
feat(cxx_indexer): distinguish field writes from reads

### PR DESCRIPTION
**Pull request by zrlk**
This PR uses ref/writes edges for field writes.
Note that intermediate fields in a path (x, y in s.x.y.z)
are not considered written to in an expression like
`s.x.y.z = 3`.

### CODE REVIEW

**Review by shahms — APPROVED** [review]

**Comment by creachadair** [comment]
This is a long-requested feature 🙂. Is there a corresponding schema change?

**Comment by jaysachs** [comment]
> This is a long-requested feature 🙂. Is there a corresponding schema change?

Once we're past the prototyping phase, yes ... I'm still interested in what is feasible, across languages, and how it matches with what people actually want.

**Comment by creachadair** [comment]
> Once we're past the prototyping phase, yes ... I'm still interested in what is feasible, across languages, and how it matches with what people actually want.

Agree. Is there a design doc or a discussion issue open for the feature? I'd like to follow along with your thoughts and results.

**Comment by zrlk** [comment]
Added issue #4688 for discussion/documentation.

**Pull request merged**
