### PR TITLE
build: update protobuf to v23.2

### PR DESCRIPTION
**Pull request by justbuchanan**

### CODE REVIEW

**Comment by justbuchanan** [comment]
Failing with:

```
ERROR: /workspace/third_party/bazel/BUILD:36:19: Generating Rust protobuf stubs [for tool] failed: (Exit 1): protoc failed: error executing command (from target //third_party/bazel:extra_actions_base_rust_proto) bazel-out/k8-opt-exec-5CCBED07/bin/external/com_google_protobuf/protoc '--plugin=protoc-gen-rust=bazel-out/k8-opt-exec-5CCBED07/bin/external/crate_index__protobuf-codegen-2.27.1/protoc-gen-rust__bin' ... (remaining 3 arguments skipped)
 --rust_out: third_party/bazel/src/main/protobuf/extra_actions_base.proto: The Rust codegen is highly experimental. Future versions will break existing code. Use at your own risk. You can opt-in by passing 'experimental-codegen=enabled' to '--rust_out'.
```

**Comment by justbuchanan** [comment]
Still running into the same issue. I tried updating rules_rust hoping it would be compatible with the new protobuf version, but it looks like that's an open issue: https://github.com/bazelbuild/rules_rust/issues/302

**Comment by justbuchanan** [comment]
@wcalandro any ideas for working around this? Updating protobuf isn't urgent, but it'd be nice to do eventually.

**Comment by justbuchanan** [comment]
Looks like the proto rules we're using from `rules_rust` are now considered legacy: https://github.com/bazelbuild/rules_rust/pull/2043

They have moved to something called "prost": https://github.com/tokio-rs/prost.

This may make it possible for us to update protobuf now.

**Comment by wcalandro** [comment]
I can look at updating rules_rust but every time I have tried updating it in the past it has failed because of cargo-bazel not working with the old version of Rust we have to use to keep the save-analysis version of the extractor/indexer building. Were you able to re-pin the deps?

**Comment by wcalandro** [comment]
Oh actually I see the error in the build logs and I have a fix for it, but it's on my workstation. I'll message you on Monday about it

**Pull request closed without merging**
