### PR TITLE
chore: perform some cleanup on the Rust indexer

### PR DESCRIPTION
**Pull request by schroederc**

### CODE REVIEW

**Comment by wcalandro** [comment]
Please run `./tools/rust/rustfmt.sh` (requires rust to be installed locally). I'm going to be changing the repo to use the rustfmt aspect soon to alleviate thisl

**Comment by wcalandro** [comment]
I'm slightly concerned with the addition of `assert!`s (since they would panic), but they realistically should never throw so it's probably fine=.

**Comment by schroederc** [comment]
> I'm slightly concerned with the addition of `assert!`s (since they would panic), but they realistically should never throw so it's probably fine=.

The asserts are maintaining the invariant already expressed here: https://github.com/kythe/kythe/pull/5356/files#diff-cb12149740fdf097c5ef11d74c7ec519d615b38d7a13e0bb12fd3c81166852f7R293

**Comment by wcalandro** [comment]
Ah that's fair

**Comment by wcalandro** [comment]
rustfmt is still unhappy. I would double-check that your IDE isn't trying to format some of the files itself as Google uses a specific rustfmt.toml (present in tools/rust/rustfmt.toml)

**Review by shahms — APPROVED** [review]

**Review by wcalandro — APPROVED** [review]

**Pull request merged**
