### PR TITLE
fix(rust_indexer): Fix proxy indexer

### PR DESCRIPTION
**Pull request by wcalandro**

### CODE REVIEW

**Review by jaysachs — COMMENTED** [review]
I sorta wish this was 3 separate PRs:

1. `hex` -> `base64` dependency
2. removal of path from `FileProvider` methods
3. the actual fix (`"true"` -> `true`)

**Comment by shahms** [comment]
Why remove path when it exists on the underlying RPC?

**Comment by wcalandro** [comment]
> I sorta wish this was 3 separate PRs:
> 
> 1. `hex` -> `base64` dependency
> 2. removal of path from `FileProvider` methods
> 3. the actual fix (`"true"` -> `true`)

I agree that the FileProvider change could probably be broken out, but the "true" -> true change and the hex -> base64 change are both part of the fix

**Comment by wcalandro** [comment]
> Why remove path when it exists on the underlying RPC?

Based on looking at other indexers that utilize the proxy interface, the precedent is to completely ignore the path argument.

**Comment by shahms** [comment]
> > Why remove path when it exists on the underlying RPC?
> 
> Based on looking at other indexers that utilize the proxy interface, the precedent is to completely ignore the path argument.

Right, but it exists to allow for implementations to ignore either and provide better diagnostics in either case.

**Pull request merged**
