### PR TITLE
feature: Add a VName specification for TypeScript Indexer

### PR DESCRIPTION
**Pull request by ayazhafiz**
#3779

Discussion wanted.

In progress:
- [x] VName specification
  - [x] Signature format
    - [x] declarations
  - [x] Corpus format
  - [x] Root format
  - [x] Path format
  - [x] Language format
- [x] Specification tests
- [x] Extension of TypeScript indexer to support specification

TODO:
- [ ] Move specification to another file? Discussion wanted.
- [x] Import/export/better module specification

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@evmar

**Comment by ayazhafiz** [comment]
Adding support for references to getters and setters requires context of their usage, because an identifier with a getter and setter has two explicit declarations. A decent approach seems to be to reference all property accesses to their getters, and all assignments to their setters.

```typescript
class A {
  get foo() { return this._foo; }
  set foo(newFoo) { this._foo = newFoo; }
  
  method() {
    let f = this.foo; // ref A.foo#getter
    this.foo = f; // ref A.foo#setter
  }
}
```

**Comment by ayazhafiz** [comment]
> ```ts
> class A {
>   get foo() { return this._foo; }
>   set foo(newFoo) { this._foo = newFoo; }
>   
>   method() {
>     let f = this.foo; // ref A.foo#getter
>     this.foo = f; // ref A.foo#setter
>   }
> }
> ```

The format now is refer to getters in the same manner other class members are (guaranteeing that there is a class member of form `Class.foo` for a getter `foo`) and setters via `Class.foo:setter`. Switched to a colon as to not interfere with the pound sign used for type namespace signatures (such as `Interface#type`).

**Comment by evmar** [comment]
This looks like it's on the right track, but you should split the getter/setter impl from the declaration spec stuff, because they are independent from each other and each will probably need a bit of iteration.

**Pull request closed without merging**
