### PR TITLE
feat(tooling): add a flag to ignore conflicting /kythe/code facts

### PR DESCRIPTION
**Pull request by BrianWieder**
Adding a flag to the verifier to ignore conflicting /kythe/code facts.

### CODE REVIEW

**Comment by d4n1elchen** [comment]
Some more context for this PR: there are some conflicting /kythe/code facts generated because of C++'s template instantiation, which in my case is inevitable because they are used in the dependency of the tested file.

**Review by shahms — APPROVED** [review]

**Comment by jaysachs** [comment]
I would be very interested in a pointer to the failures you're observing that motivated this CL.

**Comment by d4n1elchen** [comment]
I realized that this PR doesn't prevent `is_ok` from flipping. We might need additional PR to fix that.

**Pull request merged**
