### PR TITLE
fix(extractors): use distinct proto meta files for cc_proto_library

### PR DESCRIPTION
**Pull request by shahms**
It appears as though the `--cc_proto_library_header_suffixes` flag works for the .meta files (after manual testing), thus we can use distinct .meta files generated by whatever the source tree in question expects, rather than the version used to compile our release.

### CODE REVIEW

**Comment by justbuchanan** [comment]
Thanks! I like this approach much better than requiring client repos to compile the plugin from source.

**Comment by justbuchanan** [comment]
Do we still need the plugin for anything if this approach works?

**Comment by justbuchanan** [comment]
The new toolchain needs to be added to `kythe/release/release.BUILD` as well.

**Comment by shahms** [comment]
> Do we still need the plugin for anything if this approach works?

Users should not, but the plugin is used by some unittests as you can't customize bazel flags from bazel rules :-)

The embedded metadata is still my preferred approach, but can't be done without generating the entire file with the current structure of the proto rules and proto compiler.

**Comment by shahms** [comment]
Update, PTAL?

**Pull request merged**
