### PR TITLE
chore(cxx): s/absl::optional/std::optional/g

### PR DESCRIPTION
**Pull request by justbuchanan**

### CODE REVIEW

**Comment by shahms** [comment]
Nice, thanks! I'd definitely update the BUILD rules here; it should be just a matter of deleting the `"@com_google_absl//absl/types:optional"`  dep everywhere.

**Comment by justbuchanan** [comment]
> Nice, thanks! I'd definitely update the BUILD rules here; it should be just a matter of deleting the `"@com_google_absl//absl/types:optional"` dep everywhere.

Done

**Review by shahms — APPROVED** [review]

**Comment by justbuchanan** [comment]
looks like I need to change over `nullopt` as well

**Review by shahms — APPROVED** [review]

**Comment by justbuchanan** [comment]
std::string_view didn't go well, so I'll drop this one too for now

**Comment by shahms** [comment]
This doesn't have any of the problems that string_view does, AFAIK.  string_view is special for reasons which don't apply to optional.

**Comment by justbuchanan** [comment]
Ok, I'll give it a shot :)

**Pull request merged**
