### PR TITLE
Add Scala indexer.

### PR DESCRIPTION
**Pull request by johnedmonds**
This is a continuation of rbraunstein's work in https://github.com/kythe/kythe/issues/1239.

I found a copy of the old code and added some fixes and features so it works on the current Kythe version.

### CODE REVIEW

**Comment by shahms** [comment]
Thanks for reviving this! I think this has languished for so long because none of the core members use or read Scala.

Is there a specific purpose for this to be in the Kythe primary repository? We don't particularly want to have code which is unmaintained by us in the repository, as we'd be unable to provide any support, guidance or updates for it.

**Comment by ron-stripe** [comment]
Is there a repo or a "contrib" subdir this can go in?
I didn't see you found a way to revive it months ago. Thank you!

I'd like to be able to use it at Stripe (where we have a lot of scala folk), but I want the provenance settled first (part of googles open source policy etc).

**Comment by jsachs-google** [comment]
Thanks for the ping.

I just added a kythe-contrib repository.

**Comment by johnedmonds** [comment]
@jaysachs Would I just want to move this code with the same structure over to github.com/kythe/kythe-contrib (and make publically visible anything necessary from github.com/kythe/kythe)?

**Comment by jaysachs** [comment]
> @jaysachs Would I just want to move this code with the same structure over to github.com/kythe/kythe-contrib (and make publically visible anything necessary from github.com/kythe/kythe)?

Conceptually yes; I'm now curious just how much would need to be opened up in the main repo. How extensive would that visibility change be?

**Comment by jaysachs** [comment]
> I'm guessing we'd get away with little to no change for now. I suppose I'm mostly thinking ahead to whether there's a way to share the logic for generating JVM signatures so we can link together the graphs generated for Java<->.jar<->Scala.

Those are definitely reasonable things to want to do, but maybe tackle the sharing visibility when you work on the Java/Scala interop.

**Comment by johnedmonds** [comment]
@jaysachs https://github.com/kythe/kythe/pull/5094 should be the only visibility changes needed. Sent out the PR for kythe-contrib here: https://github.com/kythe/kythe-contrib/pull/1

**Pull request closed without merging**
