### PR TITLE
chore: update npm managed dependencies

### PR DESCRIPTION
**Pull request by shahms**

### CODE REVIEW

**Comment by schroederc** [comment]
Update `kythe/typescript/*` to match.

**Comment by shahms** [comment]
I have no idea how to go about doing that, the instructions from the README just result in a an exception from the yarn command.

**Comment by evmar** [comment]
Can you paste the error message?

**Comment by shahms** [comment]
Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'

some interneting suggests I need to set a proper NODE_PATH

**Comment by evmar** [comment]
What command did you run to get that error?  I have never seen that one before...

**Comment by shahms** [comment]
It was essentially the same as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933229
(`apt-get install yarnpkg` => yarnpkg fail, etc.)

**Comment by evmar** [comment]
How does it make sense that the bug is "resolved" when the binary doesn't work unless you set some obscure environment variable argh.

**Comment by shahms** [comment]
PTAL

**Pull request merged**
