### PR TITLE
use the first token in the file as the module link

### PR DESCRIPTION
**Pull request by evmar**
See discussion in the commit message.

### CODE REVIEW

**Comment by evmar** [comment]
This feels wrong to me, so your advice on how to fix it is welcomed.

**Comment by zrlk** [comment]
[ref/file](https://kythe.io/docs/schema/#reffile) is probably the right thing for this (though the example in the schema doc is mismatched somehow)

**Comment by evmar** [comment]
@zrlk do you know if ref/file will do the right thing in the Google-internal xref tool?

**Comment by evmar** [comment]
I convinced myself that this is actually the best we can do.

**Pull request merged**
