### PR TITLE
feat(java_common): improve JDK19 source compatibility

### PR DESCRIPTION
**Pull request by shahms**
Note: there remain a pair of test failures when running tests under JDK19, but those will be addressed in the future. This is enough to get things working for now.

### CODE REVIEW

**Review by jaysachs — APPROVED** [review]

**Comment by meteorcloudy** [comment]
This change isn't going to be compatible with Bazel@HEAD or the upcoming Bazel 6.0 release.
See https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2727#01845a28-fd78-4548-b5d4-4aec531d20cd
```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-j2dn/bazel-downstream-projects/kythe/WORKSPACE:141:23: //external:remotejdk19_linux: no such attribute 'exec_compatible_with' in 'http_archive' rule
ERROR: error loading package 'external': Package 'external' contains errors
Traceback (most recent call last):
  File "bazelci.py", line 3609, in <module>
    sys.exit(main())
  File "bazelci.py", line 3576, in main
    execute_commands(
  File "bazelci.py", line 1301, in execute_commands
    bazel_version = print_bazel_version_info(bazel_binary, platform)
  File "bazelci.py", line 1544, in print_bazel_version_info
    execute_command(
  File "bazelci.py", line 2270, in execute_command
    return subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
```

**Comment by shahms** [comment]
Thanks for the heads-up.  I'll double check, but ISTR that using `target_compatible_with` breaks *now*, any recommendations there?

**Comment by shahms** [comment]
This was changed in https://github.com/bazelbuild/bazel/commit/d5559c16ac008b86345fbbade5d600181a2fce6f in an incompatible fashion; there's no way to support both 5.x and 6.0 without awkward version checks.

**Comment by meteorcloudy** [comment]
@comius Have you ever dealt with similar problem? What's the best way to check the Bazel version or check which attribute name to use?

**Comment by shahms** [comment]
https://github.com/kythe/kythe/pull/5437 (isn't pretty, but should work)

**Pull request merged**
