### PR TITLE
chore(cxx): s/absl::string_view/std::string_view/g

### PR DESCRIPTION
**Pull request by justbuchanan**
The only change I reverted was in parsetextproto.h, which defines its own mock of absl::string_view

### CODE REVIEW

**Comment by shahms** [comment]
You'll need to re-run clang-format on the changed files, change the `#include "absl/strings/string_view.h" => "#include <string_view>` and update the BUILD file dependencies as well.

One possible complication here is that internally `absl::string_view` is *mostly* equivalent to `std::string_view` except in some more exotic (for google3) environments. I don't *think* we care about those, but IIRC one of them is macOS, so we may.

**Comment by justbuchanan** [comment]
I updated `#include`s and reran clang-format. Is there a good automated way to prune unused BUILD deps in the open source world?

**Comment by shahms** [comment]
Not for C++, sadly. Gazelle works for more languages than Go these days, but we don't even use it for that at the moment.

**Comment by shahms** [comment]
Actually, I think you can leave the build dependency. ISTR that string_view is included in the "strings" umbrella library which has a bunch of other stuff. It's probably not worth disentangling that at the moment.

**Comment by shahms** [comment]
The current diff is potentially a difference between clang-format-11 (from the GCB worker) and a more recent version of clang-format on your machine. We may need to update the clang-format version on GCB as 11 no longer installs on our workstations when last I checked.

**Comment by justbuchanan** [comment]
I'll take a look at updating the GCB worker

**Comment by justbuchanan** [comment]
The debian package repository shows clang-format-N for versions 11 to 17. Not sure which one we want.

On my machine, `clang-format --version` says clang-format "google3-trunk" and a commit hash.

**Comment by shahms** [comment]
Yes, the default internal version is compiled from trunk (which is why we hard-code a specific version in the pre-commit config).  14 is probably reasonable as it was released  25 March 2022

**Comment by shahms** [comment]
Thanks!

**Pull request merged**
