### PR TITLE
chore(javascript): run `npm audit fix --force`

### PR DESCRIPTION
**Pull request by justbuchanan**
This updates packages to fix some known known vulnerabilities. Should clean up a couple of our dependabot alerts.

### CODE REVIEW

**Comment by shahms** [comment]
Error: Expected package major version to equal @build_bazel_rules_nodejs major version
    @bazel/jasmine - 5.4.0  
    @build_bazel_rules_nodejs - 3.2.3
  See https://github.com/bazelbuild/rules_nodejs/wiki/Avoiding-version-skew

**Comment by justbuchanan** [comment]
I tried updating @build_bazel_rules_nodejs and now there's a dependency cycle somewhere.

```
ERROR: Failed to load Starlark extension '@rules_nodejs//nodejs:providers.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @rules_nodejs
This could either mean you have to add the '@rules_nodejs' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.243s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I tried grepping for "@rules_nodejs" and I'm not seeing it anywhere.

**Comment by shahms** [comment]
It looks like upstream substantially changed the installation procedure (or at least the Starlark file interdependencies) such that we'd need a 3-phase setup routine to keep working.  Right now, we want to do all of the setup in setup.bzl then use the repositories defined there in external.bzl, but the nodejs rules require defining a bunch of their own repositories via the `build_bazel_rules_nodejs_dependencies` macro. Bazel external dependency management remains terrible.

**Comment by shahms** [comment]
Updating rules_nodejs remains a huge PITA. It's likely you'll either need to do so incrementally (to 3.8.0 I think?) or do a larger removal and migration to the current documented practices.

**Pull request closed without merging**
