### PR TITLE
Use TypeScript ScriptElementKind to determine node context

### PR DESCRIPTION
**Pull request by ayazhafiz**
Refactors marked source generation to build a node's declaration context
using its type and the `ts.ScriptElementKind`.

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@kythe ptal

**Comment by shahms** [comment]
Cody and Luke are the most familiar with marked source.

**Comment by ayazhafiz** [comment]
@kythe could this be reviewed?

**Comment by shahms** [comment]
@zrlk @schroederc can you take a look at this?

**Comment by ayazhafiz** [comment]
I am no longer at Google, I cannot meaningfully follow up on this. Closing.

**Pull request closed without merging**
