### PR TITLE
chore: increase bazel version limit to 0.24

### PR DESCRIPTION
**Pull request by jaysachs**

### CODE REVIEW

**Comment by shahms** [comment]
This fails with `--config=remote` (and thus will likely fail on buildbot as well)
```
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/
default/BUILD:57:1: @bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8: no such attribute 'dynamic_runtime_libs' in 'cc_toolchain' r
ule                                             
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/
default/BUILD:57:1: @bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8: no such attribute 'static_runtime_libs' in 'cc_toolchain' ru
le                                                                 
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/
default/BUILD:87:1: @bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-armeabi-v7a: no such attribute 'dynamic_runtime_libs' in 'cc_too
lchain' rule                                                                                                                 
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/
default/BUILD:87:1: @bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-armeabi-v7a: no such attribute 'static_runtime_libs' in 'cc_tool
chain' rule                                                                              
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/
default/BUILD:57:1: Target '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:compiler_deps' contains an error and its package is in error and ref
erenced by '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8'
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/
default/BUILD:57:1: Target '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:empty' contains an error and its package is in error and referenced
by '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8'
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/
default/BUILD:47:1: Target '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-armeabi-v7a' contains an error and its package is in err
or and referenced by '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:toolchain'
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_toolchains/configs/ubuntu16_04_clang/1.1/bazel_0.20.0/
default/BUILD:47:1: Target '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:cc-compiler-k8' contains an error and its package is in error and re
ferenced by '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:toolchain'
ERROR: /usr/local/google/home/shahms/.cache/bazel/_bazel_shahms/f0c8a49cbf1bfaa82de86be744427f4b/external/bazel_tools/tools/cpp/BUILD:52:1: every rule of type cc_tool
chain_alias implicitly depends upon the target '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:toolchain', but this target could not be found b
ecause of: Target '@bazel_toolchains//configs/ubuntu16_04_clang/1.1/bazel_0.20.0/default:toolchain' contains an error and its package is in error
ERROR: Analysis of target '//kythe/cxx/tools/fyi/testdata:basic' failed; build aborted: Analysis failed
INFO: Elapsed time: 6.682s                                   
```

**Comment by shahms** [comment]
Actually, it works on buildbot because buildbot is installing an older version of bazel.  This will break those of us who use --config=remote to speed up compiles, though.

**Comment by shahms** [comment]
And will fail to work when buildbot updates to a newer version of Bazel.

**Comment by jaysachs** [comment]
> And will fail to work when buildbot updates to a newer version of Bazel.

I'm confused, can you clarify your comments?

Data points:

- This PR doesn't cause a failure in buildbot-launched buildbot builds, right, in particular if buildbot is on an older version.
- This PR builds successfully locally.
- You're saying that if we update buildbot to e.g. 0.24 that it will start failing? Or that because of some incompatibility between what buildbot is running and 0.24 that remote builds fail? If we updated buildbot to 0.24, presumably that would go away?

**Comment by shahms** [comment]
`bazel build --config=remote` fails with bazel 0.24.0 (and no further changes) due to the remote config using a toolchain config from 0.20.0.  0.22 is the oldest compatible release.  If buildbot is updated to 0.24 it, too, will fail due to incompatible toolchain definitions. #3652 includes the `.bazelrc` changes to fix the issues (I think) and updates buildbot.

**Pull request closed without merging**
