### PR TITLE
feat(build): switch to an autoconfigured ubuntu 18.04 image and C++17

### PR DESCRIPTION
**Pull request by shahms**

### CODE REVIEW

**Comment by schroederc** [comment]
Buildkite is still broken due to brotli

**Comment by schroederc** [comment]
Buildkite is still broken due to brotli

**Comment by shahms** [comment]
Yeah, but it's broken because it doesn't like the warning option name. Fix in flight.

**Comment by schroederc** [comment]
There's also some new looking warnings from `com_google_absl` and `se_haxx_curl`.

**Comment by shahms** [comment]
PTAL

**Pull request merged**
