### PR TITLE
chore(typescript_indexer): lint

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
cc @ayazhafiz I'm not sure if this conflicts with #3090.
Feel free to just pull this commit into your branch (and clobber my attribution if you need to).

**Comment by ayazhafiz** [comment]
I think this is good to be merged separately, but let's see if we can do a miss linting fix (https://github.com/google/gts) to catch everything at once

**Comment by zzmp** [comment]
Note that gts and clang-format (which was specified in the package.json) format the file differently.
Is there a preference over which to use? If the preference is gts, then the package.json should be updated so that other contributors are able to autoformat correctly.

**Comment by creachadair** [comment]
> Note that gts and clang-format (which was specified in the package.json) format the file differently.
> Is there a preference over which to use? If the preference is gts, then the package.json should be updated so that other contributors are able to autoformat correctly.

As a rule of thumb we've generally tried to use clang-format where it's applicable. I don't think many of the Kythe team use much TS, though. Given a choice of options I'd suggest going with whatever Google uses for TS internally, since all this code will wind up having to get imported to Google anyway.

**Comment by ayazhafiz** [comment]
> If the preference is gts, then the package.json should be updated so that other contributors are able to autoformat correctly.

@zzmp Can we pull out just tslint from gts and keep clang-format as is? I agree with @creachadair that clang-format is more applicable.

Sorry if my suggestion of gts was bad, I just meant that we should use the same lint rules they use. I'm happy to do this if you want; my bad for not being more clear.

**Comment by zzmp** [comment]
Yes. Hold off on any review - I'm going to redo this and force-push over the existing commits.

**Comment by evmar** [comment]
Confusingly, the "gts" ("google typescript') project on github is made by a group unrelated to the Google TypeScript team.  :(

**Comment by evmar** [comment]
Is this still relevant?  (Sorry, going through unmerged PRs now and saw this...)

**Comment by shahms** [comment]
Given the lack of response to Evan in June, I'm going to close this. Feel free to re-open if it's still relevant. Thanks!

**Pull request closed without merging**
