### PR TITLE
fix: check for sentinel versions of llvm/clang in check.sh

### LINKED ISSUE #3324: Unable to build on macOS after #3308
Since submission of #3308, I am no longer able to successfully run `bazel test //kythe/...` on macOS. Previously it worked, as of commit 3ecd75c3 (use the repro instructions below, _mutatis mutandis_).

## Repro

```sh
$ git checkout master
$ git pull
$ git checkout -b repro 434c0b0f
$ rm -vfr third_party/llvm/llvm  # N.B.- will force an LLVM rebuild, get coffee
$ ./tools/modules/update.sh
$ bazel test //kythe/...
```

## Expected

Build and successfully execute tests.

## Observed

```
ERROR: $HOME/software/kythe/tools/modules/BUILD:21:1: Executing genrule //tools/modules:check_modules failed (Exit 1)
Missing LLVM with ancestor 3fe1b12fca949399a3334a072ee7f96e2b6f557e (rev 345798) in third_party/llvm/llvm
Please run ./tools/modules/update.sh.
INFO: Elapsed time: 2.906s, Critical Path: 0.35s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

But note:

```
$ ls third_party/llvm/llvm/*.sentinel
third_party/llvm/llvm/3fe1b12fca949399a3334a072ee7f96e2b6f557e.sentinel
```

### PR DESCRIPTION
**Pull request by danielmoy-google**
Should fix #3324.

### CODE REVIEW

**Comment by creachadair** [comment]
That does the trick on macOS too, thanks.

**Comment by danielmoy-google** [comment]
My bad for not including it in the original change lol

**Comment by creachadair** [comment]
Please do flesh out the commit log before landing this, though. :)

**Comment by danielmoy-google** [comment]
> Please do flesh out the commit log before landing this, though. :)

Yup will do

**Pull request merged**
