### PR TITLE
build: update to a tagged version of the go-cmp module

### PR DESCRIPTION
**Pull request by creachadair**

### CODE REVIEW

**Comment by shahms** [comment]
That go test failure seems unrelated, but I'd appreciate it if you could take a quick look to verify

**Comment by creachadair** [comment]
I am pretty sure that failure is not related. It works locally:

```
$ go test -race -cpu=1,4 ./kythe/go/extractors/govname
ok  	kythe.io/kythe/go/extractors/govname	3.323s
```

**Comment by shahms** [comment]
Thanks, I'll bug @schroederc to look into it.

**Comment by schroederc** [comment]
The go test failure stems from this upstream change: https://go.googlesource.com/tools/+/0a99049195aff55f007fc4dfd48e3ec2b4d5f602

**Comment by creachadair** [comment]
Ah, that makes sense. In that case I'll just update the test case not to depend on that.

**Pull request merged**
