### PR TITLE
[fuchsia_extractor] Don't pack rlib files by default

### PR DESCRIPTION
**Pull request by filmil**
This change adds a flag --withrlibs, false by default, which when set
causes the extractor to package rlibs files for compilation replay.

However, since the current rust indexer does not use that analysis method,
the default behavior is to *not* package these files.

Fixes: #5084

### CODE REVIEW

**Comment by filmil** [comment]
@wcalandro PTAL.
I tested this change locally (in addition to the tests) and it seems to behave as advertised.

**Review by wcalandro — APPROVED** [review]

**Comment by shahms** [comment]
Minor rust-format changes:
```
Diff in /workspace/kythe/rust/fuchsia_extractor/src/bin/main.rs at line 613:
     quiet: bool,
     /// If set, the `rlib` files are packaged into kzip files too.
     with_rlibs: bool,
-
 }
 
 fn main() -> Result<()> {
```

**Comment by wcalandro** [comment]
Changes look good, please run `./tools/rust/rustfmt.sh` to format the code.

**Pull request merged**
