### PR TITLE
Support skipping 'go mod vendor' invocation.

### PR DESCRIPTION
**Pull request by svaiyapu**
In some customer go corpuses, it is customery to do `go mod vendor`
and check-in the vendor directory.  This may be due to accessing
protected vendor code.  So, support skipping 'go mod vendor' during
analyze_packages upon a envrionment variable.

ENV variable: KYTHE_SKIP_MOD_VENDOR set to one of values: ('1', 'True' or 'true')

Testing:
  - Built golang-extracter docker image
  - Ran the image on a sample corpus with KYTHE_SKIP_MOD_VENDOR env var set
  - Ensured that `go mod vendor` step is skipped.
  - Also, `bazel build //... && bazel test //...` and ensured success.

### CODE REVIEW

**Comment by svaiyapu** [comment]
Trying to look up the Lint error, but getting 

```
You do not have sufficient permissions to view this page
There was an error while loading [/cloud-build/builds/a14b2b2e-a60f-42e0-8ef5-e222ad2c7824?project=714676182536](https://pantheon.corp.google.com/cloud-build/builds/a14b2b2e-a60f-42e0-8ef5-e222ad2c7824%3Fproject%3D714676182536?project=714676182536).

You are missing the following required permissions:
Project  714676182536
cloudbuild.builds.get
```

**Comment by shahms** [comment]
```
In kythe/go/extractors/cmd/gotool/analyze_packages.sh line 68:
if ! [ -n "$SKIP_MOD_VENDOR" ]; then
   ^-- SC2237: Use [ -z .. ] instead of ! [ -n .. ].

For more information:
  https://www.shellcheck.net/wiki/SC2237 -- Use [ -z .. ] instead of ! [ -n ....
```

**Comment by svaiyapu** [comment]
Committed fix for the lint issue.  PTAL.  Thanks.

**Review by justbuchanan — APPROVED** [review]

**Pull request merged**
