### PR TITLE
refactor(typescript_indexer): constrain param type on `IndexerHost#emit`

### PR DESCRIPTION
**Pull request by ayazhafiz**
`IndexerHost#emit` should only accept JSON Kythe facts and edges. This
is a breaking change but as far as I remember, it should only impact a
small amount of (if any) users.

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@evmar PTAL

**Comment by ayazhafiz** [comment]
@evmar PTAL

**Comment by evmar** [comment]
Still relevant?

**Comment by ayazhafiz** [comment]
nah its covered in the cleanup PR

**Pull request closed without merging**
